on:
  schedule:
    - cron: "30 00 * * 0"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Renovate
        uses: renovatebot/github-action@v40.3.3
        with:
          configurationFile: .github/renovate-config.js
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
